---
name: 'Continuous Integration'

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: 'Go Test'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
        with:
          fetch-depth: 1
      - uses: 'cedrickring/golang-action@1.6.0'
        with:
          args: 'make test'
